version: 2.1
jobs:
  build:
    docker:
      - image: jtblatt/everscale-build:04-09-20
    steps:
      - checkout
      - run:
          name: "debug build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              cmake -DCMAKE_BUILD_TYPE=DEBUG . && make && make test
      - run:
          name: "tsan build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              cmake -DCMAKE_BUILD_TYPE=TSAN . && make && make test
      - run:
          name: "asan build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              cmake -DCMAKE_BUILD_TYPE=ASAN . && make && make test
      - run:
          name: "release build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              cmake -DCMAKE_BUILD_TYPE=RELEASE . && make && make test
