version: 2.1
jobs:
  build:
    docker:
      - image: jtblatt/everscale-build:01-10-21b
    steps:
      - checkout
      - run:
          name: "debug"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              export EXTRA_CFLAGS=-DESB_CI_BUILD
              export EXTRA_CXXFLAGS=-DESB_CI_BUILD
              BUILD_TYPE=DEBUG cmake . && make && make test
      - run:
          name: "tsan"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              export EXTRA_CFLAGS=-DESB_CI_BUILD
              export EXTRA_CXXFLAGS=-DESB_CI_BUILD
              BUILD_TYPE=TSAN cmake . && make && make test
      - run:
          name: "asan"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              export EXTRA_CFLAGS=-DESB_CI_BUILD
              export EXTRA_CXXFLAGS=-DESB_CI_BUILD
              BUILD_TYPE=ASAN cmake . && make && make test
      - run:
          name: "release"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              export EXTRA_CFLAGS=-DESB_CI_BUILD
              export EXTRA_CXXFLAGS=-DESB_CI_BUILD
              BUILD_TYPE=RELEASE cmake . && make && make test
      - run:
          name: "allocators disabled"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              export EXTRA_CFLAGS=-DESB_CI_BUILD
              export EXTRA_CXXFLAGS=-DESB_CI_BUILD
              BUILD_TYPE=DEBUGNOPOOL cmake . && make && make test
