version: 2.1
jobs:
  build:
    docker:
      - image: jtblatt/everscale-build:01-10-21
    steps:
      - checkout
      - run:
          name: "debug build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              BUILD_TYPE=DEBUG cmake . && make && make test
      - run:
          name: "tsan build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              BUILD_TYPE=TSAN cmake . && make && make test
      - run:
          name: "asan build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              BUILD_TYPE=ASAN cmake . && make && make test
      - run:
          name: "release build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              BUILD_TYPE=RELEASE cmake . && make && make test
      - run:
          name: "nopool build"
          command: |
              set +e
              export CC=clang
              export CXX=clang++
              export CLANG_FORMAT=clang-format
              export CTEST_OUTPUT_ON_FAILURE=1
              export VERBOSE=1
              BUILD_TYPE=DEBUGNOPOOL cmake . && make && make test
