BASE=../..

INCLUDE = \
-I$(BASE)/sparrowhawk/test_framework

SOURCES=\
ESTFDate.cpp\
ESTFConcurrencyDecorator.cpp\
ESTFConcurrencyComposite.cpp\
ESTFComponentThread.cpp\
ESTFComposite.cpp\
ESTFRandomizedDecorator.cpp\
ESTFRepetitionDecorator.cpp\
ESTFResultCollector.cpp\
ESTFThread.cpp

LIB=$(BASE)/lib/libtest_framework

all: $(LIB)

include $(BASE)/GNUmakevars
