#ifndef ES_CONFIG_H
#define ES_CONFIG_H

#define ES_VERSION_STRING ".."
#define ES_VERSION_MINOR
#define ES_VERSION_MAJOR
#define ES_VERSION_PATCH

/* #undef ESB_BIG_ENDIAN */
#define ESB_LITTLE_ENDIAN 1

#define HAVE_INTTYPES_H 1

#ifdef HAVE_INTTYPES_H
#include <inttypes.h>
#endif

#define HAVE_STDINT_H 1

#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif

#define HAVE_WORDSIZE 1

#ifndef HAVE_WORDSIZE
#error "Cannot determine wordsize"
#endif

#if __WORDSIZE == 64
#define ESB_64BIT
#elif __WORDSIZE == 32
#define ESB_32BITA
#else
#error "Invalid wordsize"
#endif

#define HAVE_X86_ASM 1

#define SIZEOF_CHAR 8
#define SIZEOF_UNSIGNED_CHAR 8
#define SIZEOF_SHORT 16
#define SIZEOF_UNSIGNED_SHORT 16
#define SIZEOF_INT 32
#define SIZEOF_UNSIGNED_INT 32
#define SIZEOF_LONG 64
#define SIZEOF_UNSIGNED_LONG 64
#define SIZEOF_LONG_LONG 64
#define SIZEOF_UNSIGNED_LONG_LONG 64

#define HAVE_SYS_TYPES_H 1
#define HAVE_OFF_T 8
#define HAVE_SIZE_T 8
#define HAVE_SSIZE_T 8

#define HAVE_PTHREAD_H 1
#define ESB_THREAD_ID_FORMAT PRId64
#define HAVE_PTHREAD_T 8
#define HAVE_PTHREAD_MUTEX_T 40
#define HAVE_PTHREAD_MUTEX_INIT 1
#define HAVE_PTHREAD_MUTEX_DESTROY 1
#define HAVE_PTHREAD_MUTEX_LOCK 1
#define HAVE_PTHREAD_MUTEX_TRYLOCK 1
#define HAVE_PTHREAD_MUTEX_UNLOCK 1
#define HAVE_PTHREAD_RWLOCK_T 56
#define HAVE_PTHREAD_RWLOCK_INIT 1
#define HAVE_PTHREAD_RWLOCK_DESTROY 1
#define HAVE_PTHREAD_RWLOCK_RDLOCK 1
#define HAVE_PTHREAD_RWLOCK_WRLOCK 1
#define HAVE_PTHREAD_RWLOCK_TRYRDLOCK 1
#define HAVE_PTHREAD_RWLOCK_TRYWRLOCK 1
#define HAVE_PTHREAD_RWLOCK_UNLOCK 1
#define HAVE_PTHREAD_COND_T 48
#define HAVE_PTHREAD_COND_INIT 1
#define HAVE_PTHREAD_COND_DESTROY 1
#define HAVE_PTHREAD_COND_SIGNAL 1
#define HAVE_PTHREAD_COND_WAIT 1
#define HAVE_PTHREAD_COND_BROADCAST 1
#define HAVE_PTHREAD_CREATE 1
#define HAVE_PTHREAD_JOIN 1
#define HAVE_PTHREAD_SELF 1

#define HAVE_SCHED_H 1
#define HAVE_SCHED_YIELD 1

#define HAVE_SIGNAL_H 1
#define HAVE_SIGACTION 1
#define HAVE_STRUCT_SIGACTION 1

#define HAVE_STDIO_H 1
#define ALLOW_CONSOLE_LOGGING 1
#define HAVE_VFPRINTF 1
#define HAVE_SNPRINTF 1

#define HAVE_STDARG_H 1
#define HAVE_VA_START 1
#define HAVE_VA_END 1

#define HAVE_ASSERT_H 1
#define HAVE_ASSERT 1

#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_FREE 1
#define HAVE_ABORT 1
#define HAVE_RAND_R 1
#define HAVE_RAND_MAX 1

#define HAVE_NETINET_IN_H 1
#define HAVE_STRUCT_SOCKADDR_IN 1
#define HAVE_INADDR_ANY 1
#define HAVE_HTONL 1
#define HAVE_HTONS 1
#define HAVE_NTOHL 1
#define HAVE_NTOHS 1

#define HAVE_NETDB_H 1
#define HAVE_HOSTENT_T 1
#define HAVE_GETHOSTBYNAME_R_LINUX 1

#define HAVE_ARPA_INET_H 1
#define HAVE_INET_PTON 1
#define HAVE_INET_NTOP 1

#define HAVE_STRING_H 1
#define HAVE_MEMSET 1
#define HAVE_MEMCPY 1
#define HAVE_STRERROR_R 1
#define HAVE_STRNCPY 1
#define HAVE_STRLEN 1
#define HAVE_STRCAT 1
#define HAVE_MEMMOVE 1

#define HAVE_UNISTD_H 1
#define HAVE_GETHOSTNAME 1
#define HAVE_CLOSE 1

#define HAVE_SYS_PARAM_H 1
#define HAVE_MAXHOSTNAMELEN 1

#define HAVE_SYS_SOCKET_H
#define UNIX_NONBLOCKING_CONNECT_ERROR
#define HAVE_STRUCT_SOCKADDR
#define HAVE_SOCKLEN_T
#define HAVE_SOCKET
#define HAVE_BIND
#define HAVE_LISTEN
#define HAVE_ACCEPT
#define HAVE_CONNECT
#define HAVE_SEND
#define HAVE_RECV
#define HAVE_GETPEERNAME
#define HAVE_SETSOCKOPT
#define HAVE_GETSOCKOPT

#define HAVE_SYS_IOCTL_H
#define HAVE_IOCTL
#define USE_IOCTL_FOR_NONBLOCK

#define HAVE_SYS_TIME_H
#define HAVE_STRUCT_TIMEVAL
#define HAVE_GETTIMEOFDAY

#define HAVE_TIME_H
#define HAVE_TIMESPEC_T
#define HAVE_NANOSLEEP
#define HAVE_TIME_T
#define HAVE_TIME

#define HAVE_SYS_SELECT_H
#define UNIX_SELECT_SEMANTICS
#define HAVE_SELECT

#define HAVE_ERRNO_H
#define HAVE_ERRNO_T
#define HAVE_ERRNO
#define EAGAIN_AND_EWOULDBLOCK_IDENTICAL

#define HAVE_SYS_EPOLL_H
#define HAVE_STRUCT_EPOLL_EVENT
#define HAVE_EPOLL_CREATE
#define HAVE_EPOLL_CTL
#define HAVE_EPOLL_WAIT

#define HAVE_SYS_RESOURCE_H
#define HAVE_STRUCT_RLIMIT
#define HAVE_GETRLIMIT

#ifdef HAVE_ASSERT_H
#include <assert.h>
#endif

#ifndef HAVE_ASSERT
#error "assert() required"
#endif

#ifdef HAVE_STRING_H
#include <string.h>
#endif

#ifdef HAVE_STDIO_H
#include <stdio.h>
#endif

#endif
