/** @file ESFConfig.h
 *  @brief This file can be included to define the target platform's properties.
 *
 * Copyright (c) 2009 Yahoo! Inc.
 * The copyrights embodied in the content of this file are licensed by Yahoo! Inc.
 * under the BSD (revised) open source license.
 *
 * Derived from code that is Copyright (c) 2009 Joshua Blatt and offered under both
 * BSD and Apache 2.0 licenses (http://sourceforge.net/projects/sparrowhawk/).
 *
 *    $Author: blattj $
 *    $Date: 2009/05/25 21:51:08 $
 *    $Name:  $
 *    $Revision: 1.3 $
 */

#ifndef ESF_CONFIG_H
#define ESF_CONFIG_H

/** @defgroup foundation_test Foundation Unit Tests. */

#ifdef ES_LINUX
#include <ESFLinuxConfig.h>
#elif defined ES_SOLARIS
#include <ESFSolarisConfig.h>
#elif defined ES_DARWIN
#include <ESFDarwinConfig.h>
#elif defined ES_WIN32
#include <ESFWin32Config.h>
#else
// This may be generated by autoconf
#include <config.h>
#endif

#endif /* ! ESF_CONFIG_H */
